# Generated by Django 3.1.7 on 2021-07-27 09:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
