# Generated by Django 3.1.7 on 2021-07-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_investment_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.BooleanField(),
        ),
    ]
