# Generated by Django 3.1.7 on 2021-07-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210720_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='payment_wallet_address',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
