# Generated by Django 3.1.7 on 2021-07-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_appuser_payment_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appuser',
            name='bank_account_name',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='appuser',
            name='bank_account_number',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='appuser',
            name='bank_name',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='appuser',
            name='bank_type',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='appuser',
            name='country',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='appuser',
            name='dob',
            field=models.CharField(default='none', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='house_address',
            field=models.TextField(default='none', null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='id_image',
            field=models.FileField(blank=True, default='default_files/default_face.png', upload_to='account_files/id_images/'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='id_number',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='appuser',
            name='language',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='appuser',
            name='phone_no',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='appuser',
            name='place_of_work',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='appuser',
            name='place_of_work_address',
            field=models.TextField(default='none', null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='state_of_origin',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
