# Generated by Django 3.1.7 on 2021-07-27 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210727_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
