# Generated by Django 3.1.7 on 2021-07-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210727_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='status',
            new_name='paid_status',
        ),
        migrations.AddField(
            model_name='investment',
            name='peered_status',
            field=models.BooleanField(default=False),
        ),
    ]
