# Generated by Django 3.1.7 on 2021-07-21 14:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210720_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_app_id', models.CharField(default='none', max_length=500)),
                ('receiver_app_id', models.CharField(default='none', max_length=500)),
                ('proof_photo', models.FileField(blank=True, default='default_files/default_face.png', upload_to='account_files/commit_proof_photos/')),
                ('amount', models.CharField(default='none', max_length=500)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CommitSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.appuser')),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.commit')),
            ],
        ),
    ]
