# Generated by Django 3.1.7 on 2021-07-21 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_commit_commitsheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='receiver_app_id',
            new_name='receiver_app_user_id',
        ),
        migrations.RenameField(
            model_name='commit',
            old_name='sender_app_id',
            new_name='sender_app_user_id',
        ),
    ]
