# Generated by Django 3.2.5 on 2021-07-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210721_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='place_of_work',
        ),
        migrations.RemoveField(
            model_name='appuser',
            name='place_of_work_address',
        ),
        migrations.AddField(
            model_name='appuser',
            name='bank_verification_number',
            field=models.CharField(default='none', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commitsheet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
