# Generated by Django 3.1.7 on 2021-07-24 15:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20210721_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default='none', max_length=500)),
                ('who_app_user_id', models.CharField(default='none', max_length=500)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.appuser')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default='none', max_length=500)),
                ('who_app_user_id', models.CharField(default='none', max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('proof_photo1', models.FileField(blank=True, default='default_files/default.png', upload_to='app_files/proof_photos/')),
                ('proof_photo2', models.FileField(blank=True, default='default_files/default.png', upload_to='app_files/proof_photos/')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.appuser')),
            ],
        ),
        migrations.RemoveField(
            model_name='commitsheet',
            name='app_user',
        ),
        migrations.RemoveField(
            model_name='commitsheet',
            name='commit',
        ),
        migrations.DeleteModel(
            name='Commit',
        ),
        migrations.DeleteModel(
            name='CommitSheet',
        ),
    ]
