# Generated by Django 3.1.7 on 2021-07-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210724_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='package_type',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
