# Generated by Django 3.2.5 on 2021-07-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_alter_appuser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_photo',
            field=models.FileField(blank=True, default='default_files/default_face.png', upload_to='account_files/profile_photos/'),
        ),
    ]
